omni_robot:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    left_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: joint_left_bottom_wheel
        pid: {p: 1000, i: 0.1, d: 0}

    back_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: joint_top_wheel
        pid: {p: 1000, i: 0.1, d: 0}

    right_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: joint_right_bottom_wheel
        pid: {p: 1000, i: 0.1, d: 0}
